### ISSUE TITLE
New problem: compiler crashed

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/common-problems#18]
Seen in the Cloogle log: `Error: Compiler crashed: C:\PROGRA~1\Clean 2.4\Tools\Clean System 64\CleanCompiler64.exe`.

**Comment by peterachten** [comment]
Perhaps we can create an entry for this with a message going something like:

```
Hmm, you managed to crash the Clean compiler. We would really like to know how you did this. Please send an error report to clean-bugs@cs.ru.nl and include (preferably a minimal version of) your code. This will help us improve the compiler.
```

**Comment by camilstaps** [comment]
Good idea, I did this but also added a suggestion to first contact one of the instructors if you are enrolled in a programming course.

**Comment by peterachten** [comment]
I noticed, great!
