### ISSUE TITLE
New problem: = expected instead of offside token (new def)

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/common-problems#23]
Seen in the Cloogle log: `Parse error [Assignment1.icl,12;7,RHS: root expression]: = expected instead of offside token (new def)`.

**Comment by peterachten** [comment]
I'm having trouble reproducing exactly this error message. The best I can manage so far is:

```
Parse error [Errors.icl,14;10,RHS: root expression]: = <ExprWithLocals> expected instead of offside token (end group)
```

Was "<ExprWithLocals>" missing from the log?

**Comment by camilstaps** [comment]
Indeed the error message as found in the log cannot be generated by (recent versions of) the compiler. With `= <ExprWithLocals>` this reproduces it:

```clean
module test
fun
Start = 37
```

But I'm not sure if we should include errors like this here. There are many different parse errors, it will be difficult to explain them in general, and in these cases it may be more efficient to teach people to read the error message and check their code carefully. What do you think?

**Comment by peterachten** [comment]
I agree that they are difficult to explain in general. Still, it might be better to direct the user to some general instruction such as (instead of simply producing no result):

```
Parse errors usually indicate that the code is ill-formatted. The error message gives a location in the 
program code where the structure appears to be wrong. Determine what kind of language element 
the error points at (e.g. is it a function definition, or a type definition, or a type class), and check the
language report to see how these language elements should be structured. 
```

Your opinion?

**Comment by peterachten** [comment]
p.s.: I really liked your solution with the 'segmentation fault' and 'compiler crashed' error message

**Comment by camilstaps** [comment]
Sounds good; I added this almost verbatim (added some information about the structure of the error message).
