### ISSUE TITLE
New problem: segmentation fault

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/common-problems#25]
Seen in the Cloogle log: `segmentation fault`.

**Comment by peterachten** [comment]
hmm, don't know how to reproduce this one, somebody else?

**Comment by peterachten** [comment]
Perhaps do something similar as I suggest in issue #18 ?

**Comment by camilstaps** [comment]
Perhaps this one does not exist on Windows (the query was from a Mac). But I added a generic message as you suggested.
