### ISSUE TITLE
New problem: this alternative has n arguments instead of m

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/common-problems#30]
From the log: `Error [MatchStrings.icl,10,tail]: This alternative has 4 arguments instead of 1.`

**Comment by peterachten** [comment]
This is odd, there is an entry for this one:
This-alternative-has-X-arguments-instead-of-Y.md

**Comment by camilstaps** [comment]
You're right, it appeared in the log but also showed a result. Nothing to do here :)
