### ISSUE TITLE
"Unable to create new project"

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/common-problems#32]
From the log: `Unable to create new project`

Should probably go into a new `ide-errors` directory.

**Comment by peterachten** [comment]
any idea how to generate this error? read-only folder?

**Comment by dopefishh** [comment]
Maybe a disk is full

**Comment by camilstaps** [comment]
Looking at the IDE source code (`Ide/projmen.icl`) this occurs when there is no active module window. I'll add an entry.
