### ISSUE TITLE
"the specified member type is incorrect"

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/common-problems#35]
Seen in the log: `Error [ex1.icl,30,read]: the specified member type is incorrect ( context not ok)`

Probably Advanced Programming, I'm guessing a class instance with a wrong type.

**Comment by peterachten** [comment]
You get this error when you forgot to include the class constraints at the instance header declaration, but actually included them in the type instance;

Indeed, I teach my students never to include the type instance themselves to avoid this error. This is probably an error from Advanced Programming. Next week, I'll be doing overloading in my course, so I expect a number of related errors then... :-)

I'll make an entry for this.

**Comment by peterachten** [comment]
done, pull request pending

**Comment by peterachten** [comment]
hmm, something went wrong here (deja vu feeling arising):

```
Error: file 'specified-member-type-is-incorrect.md' was referenced but is not indexed - does it exist?)
Error: problem not referenced in readme: 'specified member type is incorrect' in 'compiler-errors/specified-member-type-is-incorrect.md'
```

need to go home now, so can't fix it immediately - everything looks fine at my side -

**Comment by camilstaps** [comment]
The file name did not have the `compiler-errors` bit. It's fixed. The explanation is very elaborate; thanks & have a nice weekend!

**Comment by peterachten** [comment]
Ah, silly me. Thanks for fixing!
