### ISSUE TITLE
"Error [Date.icl,29,no_of_days]: (curried) application not allowed"

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/common-problems#36]
Seen in the log: `Error [Date.icl,29,no_of_days]: (curried) application not allowed`.

Perhaps curried application in the pattern? The query before this one was `no_of_days (is_leap_year x == True) February = 29`.

**Comment by peterachten** [comment]
done, pull request is pending

**Comment by camilstaps** [comment]
Thanks!
