### ISSUE TITLE
No _system.abc

### ISSUE THREAD

**Issue by dopefishh** [clean-cloogle/common-problems#43]
**Exact error message**:

> Error: [_system.abc,]: could not be patched.

**A minimal example**:

First throw away `_system.abc`

```clean
module test; Start = 42;
```

**Comment by peterachten** [comment]
perhaps somebody accidentally threw away 'Clean System Files'?

**Comment by camilstaps** [comment]
I cannot reproduce this. When I throw away `_system.abc`, everything works fine because the object file exists. If I also remove `_system.o`, I get `Couldn't find _system.o`.

**Comment by dopefishh** [comment]
Hmm, I think it happens only when _system.abc needs to be patched. E.g. different profiling settings. I'll verify this next Monday.

**Comment by camilstaps** [comment]
I thought so as well, and tried it, but only with clm. Apparently this error is generated only by cpm.

**Comment by dopefishh** [comment]
Mystery solved.
Cpm does have better recompiling rules (e.g. detecting dynamics) so I'm not surprised.

**Comment by camilstaps** [comment]
In fact clm does a better job here. The only patching that cpm does is swapping the time profiling bit in the `.comp` header of `_system.abc`, to keep itself from searching for a `_system.dcl` to regenerate the ABC. clm just keeps the header correct as it is and knows that it never needs to regenerate this particular ABC file.
