### ISSUE TITLE
New problem: "incorrect number of members specified"

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/common-problems#44]
From the log: `Error [StdDay.icl,65,fromString]: incorrect number of members specified`

This is different from `different number of members specified`, but I don't know how to reproduce it.

**Comment by peterachten** [comment]
Hmm, can't reproduce either. A quick search in the compiler sources also didn't help. I'll ask John.

**Comment by dopefishh** [comment]
This can be reproduced by implementing a class with two class members and you only implement one.

**Comment by peterachten** [comment]
Hi Mart,

No, that would generate *different* number of members specified instead of *incorrect* number of members specified. Do you have an example?

**Comment by dopefishh** [comment]
https://cloo.gl/NjE5 (check.icl)
Something something, size dcl_members <> size icl_members.
I'll look into it

**Comment by peterachten** [comment]
I'll make an entry in cloogle
