### ISSUE TITLE
New problem: "used with wrong arity"

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/common-problems#45]
Seen in the log: `Error [TupleOverloading.icl,9,+]: + used with wrong arity`

**Comment by peterachten** [comment]
actually, quite an accurate error message... I'll add an entry

**Comment by camilstaps** [comment]
Thanks!

**Comment by camilstaps** [comment]
This error message seems to be overloaded; I now also see in the log: `Error [StdT.icl,30,toString]: T used with wrong arity`. This occurs when using a constructor with the wrong arity in a pattern, as in `f (Just _ _) = ...`.
