### ISSUE TITLE
Not enough memory to allocate heap and stack

### ISSUE THREAD

**Issue by dopefishh** [clean-cloogle/common-problems#46]
**Exact error message**:

> Not enough memory to allocate heap and stack

**A minimal example**:

```clean
module test
Start = 42
```

Depending on your system's memory:

```sh
$ clm -aC,-h,20000m test
```

**Comment by camilstaps** [comment]
Also by running any other program while requesting too much memory; this is a run time error which happens to also be present in the compiler.
