### ISSUE TITLE
Run Time Error: index out of range

### ISSUE THREAD

**Issue by dopefishh** [clean-cloogle/common-problems#48]
**What common problem is this about?**

Run Time Error: index out of range

**What would you like to see changed?**

This is not only a run-time error but can also be a compile time error, e.g.: https://github.com/clean-cloogle/common-problems/issues/44#issuecomment-423109489
Maybe we can add a note to all run-time errors that if they occur at compile-time that they should report a compiler bug.

**Comment by camilstaps** [comment]
Sounds good to me. Let's just add those lines manually as an extra solution; that keeps the format simple.
