### ISSUE TITLE
"type context should contain one or more type variables" 

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/common-problems#53]
From the log: `Error [StdT.icl,40,Start]: fromStringM:2 type context should contain one or more type variables`

**Comment by peterachten** [comment]
Hmm, I'll have a look how to produce this error

**Comment by camilstaps** [comment]
It seems this occurs when one uses a type context containing fully instantiated types only:

```clean
f :: Int -> String | toString Int
f x = toString x
```

**Comment by peterachten** [comment]
Hadn't tried that one yet...; I'll create an entry for this

**Comment by camilstaps** [comment]
Resolved in #63.
