### ISSUE TITLE
no generic instances of def for kind...

### ISSUE THREAD

**Issue by dopefishh** [clean-cloogle/common-problems#57]
**Exact error message**:

> no generic instances of def for kind {{*->*}->*}

**A minimal example**:

```clean
module test

import StdGeneric

generic def a :: a

:: T a = T (a Int)
:: Maybe a = Nothing | Just a

Start :: T Maybe
Start = def{|(*->*)->*|} (\l->Just l)
```

**Comment by camilstaps** [comment]
Is this not identical to #54? The only difference is that here you try to use a different kind.

**Comment by dopefishh** [comment]
No, the one for kind * only occurs when you have no specialization AT ALL.
If you add a specialization for Maybe for example the error changes.

This is in contrast to the other kinds, there it says it only if you have no
specialization of that particular kind.

**Comment by camilstaps** [comment]
The problem primarily has to do with the kind used in the application of the function:

```clean
generic gFun a :: a
Start :: Int
Start = gFun{|*->*|}
```

Throws this error about kind `*->*`.

When you use `gFun{|k|}`, the compiler will first collect all generic instances of kind `k`. If none are found, this error is thrown. If one or more are found, the compiler proceeds to use type information to select the right instance.
