### ISSUE TITLE
result type of dynamic must be non-unique

### ISSUE THREAD

**Issue by dopefishh** [clean-cloogle/common-problems#64]
**Exact error message**:

> result type of dynamic must be non-unique

**A minimal example**:

```clean
module test

fromDyn :: Dynamic -> *World
fromDyn (a :: *World) = a
```

**Comment by camilstaps** [comment]
Another way to trigger this error is by trying to create a dynamic with a unique value:

```clean
Start = dynamic 5 :: *Int
```
